{
    'name': 'VIT Demo POS',
    'version': '17.0.1.0.0',
    'category': 'Point of Sale',
    'summary': """Belong to VIT""",
    'author': 'Visi Intech',
    'company': 'Visi Intech',
    'maintainer': 'Visi Intech',
    'website': "https://www.Visi-Intech.com",
    'depends': ['base', 'sale', 'stock', 'point_of_sale', 'account'],
    'data': [
        # 'security/hr_security.xml',
        'security/ir.model.access.csv',
        'views/views_pos_order.xml',
        'views/views_stock_picking.xml',
        'views/views_res_partner.xml',
        'views/views_account_move.xml',
        'views/views_account_payment.xml',
        'views/views_log_code_runtime.xml',
        'views/views_log_note.xml',
        'views/menu_log_note.xml',
        'views/views_pos_session.xml',
        'views/ir_sequence_view.xml',
        'views/product_template_view.xml',
        'views/views_store_warehouse.xml',
        # 'views/views_master_type.xml',
        'views/views_master_configuration.xml',
        'views/menu_master_configuration.xml',
        'views/views_manual_sync_ss_to_mc.xml',
        'views/views_loyalty_program.xml',
        'views/views_manual_sync_mc_to_ss.xml',
        'views/views_loyalty_rule.xml',
        'views/views_loyalty_reward.xml',
        'views/views_product_pricelist.xml',
        'views/views_purchase_order.xml',
        'views/views_token_generate.xml',
        'views/views_list_license.xml',
        'views/pos_category_view.xml',
        'views/stock_picking_type_view.xml',
        'views/uom_category_view.xml',
        'views/uom_uom_view.xml',
        'views/views_account_tax_repartition_line.xml',
        'views/views_account_tax.xml',
        'views/views_product_category.xml',
        # 'views/views_product_pricelist_item.xml',
        'views/views_res_partner_title.xml',
        'views/pos_config_view.xml',
        'views/pos_payment_method_views.xml',
        'views/hr_employee_view.xml',
        'views/loyalty_card_view.xml',
        'views/account_journal_view.xml',
        'views/views_master_type.xml',
        'views/account_account_view.xml',
        'views/end_shift_view.xml',
        'views/pos_cashier_log_view.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            # 'dev_pos/static/src/css/pop_up.css',
            # 'dev_pos/static/src/xml/button.xml',
            # # 'dev_pos/static/src/xml/button_screen.xml',
            # 'dev_pos/static/src/js/button.js',
            'dev_pos/static/src/js/custom_invoice.js',
            # 'dev_pos/static/src/js/pop_up_card.js',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}