from . import pos_order
from . import stock_picking
from . import account_move
from . import account_payment
from . import res_partner
from . import log_code_runtime
from . import log_note
from . import pos_session
from . import ir_sequence
from . import stock_picking_type
from . import product_template
from . import store_warehouse
from . import pos_order_line
from . import master_type
from . import loyalty_program
from . import loyalty_rule
from . import loyalty_reward
from . import product_pricelist
from . import purchase_order
from . import token_generate
from . import list_license
from . import account_tax
from . import account_tax_repartition_line
from . import pos_category
from . import product_pricelist_item
from . import res_partner_title
from . import uom_category
from . import uom_uom
from . import product_category
from . import pos_config
from . import pos_payment_method
from . import hr_employee
from . import loyalty_card
from . import account_journal
from . import master_type
from . import account_account
from . import end_shift
from . import pos_cashier_log